### ISSUE TITLE
Consider using JSON 5 for bleep.json

### ISSUE THREAD

**Issue by hamnis** [oyvindberg/bleep#15]
https://json5.org/

**Comment by oyvindberg** [comment]
No doubt it's what json always should have been. I still think we should keep json by default though. It's ubiquitous, for better or worse.

I'm much more inclined to provide a mechanism by which you can use anything which can output json.
Let's say we perform these steps on startup:
- look for bleep.json , use if it exists
- look for bleep.* with the executable bit set. if it exists run it, and pipe the output of the program through the normal json parser

wouldn't that be neat? That way you can for instance code the build in typescript, and you pay for it by having to start node on every invocation of bleep. Or well, we could certainly cache the output by the timestamp of the executable file actually.

**Comment by Baccata** [comment]
> I'm much more inclined to provide a mechanism by which you can use anything which can output json.

I absolutely love this idea. This would totally provide the flexibility to use whatever declarative language as config, and fallback to any general purpose language when the build structure is really complex. Like, [weaver-test](https://github.com/disneystreaming/weaver-test/), which I maintain, cross-compiles most modules against 3 different axis : platform, scala-version, and cats-effect version. I would probably rather like the freedom to build bleep's configuration from a scala-cli script. 

> Or well, we could certainly cache the output by the timestamp of the executable file actually.

You'd probably need to have the executable file output a list of files/directories that should be hashed and checked, alongside the bleep config. Say you'd want to configure your build in hocon (or json5). You'd need 1 `bleep.something` script + 1 hocon/json5 file, and changing either of them should result in the invalidation of the cache.

**Comment by Baccata** [comment]
That's absolutely fair :) I'll report back when/if I find the time to experiment with a wrapper thingy.

**Comment by oyvindberg** [comment]
Superseded by #185
