### ISSUE TITLE
Naive scalafmt extraction is too naive 

### ISSUE THREAD

**Issue by Baccata** [oyvindberg/bleep#234]
Using bleep  0.0.1-M21, bleep is unable to figure out the version number if the property is formatted with spaces: : 

``` 
version = "3.6.1" 
```

additionally, it doesn't remove quotes before attempting to download the scalafmt binary, which leads to a 404. The version currently has to be written without spaces nor quotes.

**Comment by oyvindberg** [comment]
Hah, great find! This should be an easy fix
