### ISSUE TITLE
Native-image assumption is too aggressive 

### ISSUE THREAD

**Issue by Baccata** [oyvindberg/bleep#235]
Alright, this is an interesting one : I'm attempting to run bleep at $work in a self-hosted GHA. I don't have control over the runners as the infra is provided by a completely isolated team. 

* If I install bleep using the coursier channel, as you would expect, I essentially bump into [this](https://github.com/actions/runner-images/issues/6647) : the LIBC available on the runner is not matching the one that bleep was built against. 
* So I'm like "well, this is CI anyway, let's try and run bleep on JVM, shall we, it's not the end of the world right now?" Unfortunately, when checking for the version number in the build-file (in order to download the correct version), bleep presumes it's running from a native-image, and invokes a [coursier function](https://github.com/coursier/coursier/blob/c7f9658419e1fce68e5e0c222523ee8149175bd4/modules/jvm/src/main/java/coursier/jvm/Execve.java#L10) that is unavailable on JVM (only implemented for graal). 

The workaround I found is to use coursier to bootstrap the version of bleep referenced in the build file, something like : 

``` 
BLEEP_VERSION=$(cat bleep.yaml | grep '$version' | cut -d ":" -f2 |   tr -d ' ')
cs bootstrap build.bleep:bleep-cli_2.13:$BLEEP_VERSION -M bleep.Main -o bleep
```

**Comment by oyvindberg** [comment]
Hey there, thanks for testing it! I bet there are many small things like this lurking around.

Do you have any insight into this? Would it be enough if we set the GitHub runner to use an old Ubuntu runner?

**Comment by sideeffffect** [comment]
It would be still nice to be able to run Bleep just on JVM just from Maven Central, right?

**Comment by keynmol** [comment]
> Would it be enough if we set the GitHub runner to use an old Ubuntu runner?

That's how it's usually solved, yes. 
A lot of things are very slow moving so 22.04 is waaay too young to build any tools.
Plus you barely get any benefits by using it.

**Comment by oyvindberg** [comment]
Running bleep from the JVM should absolutely work! Can you try running from the JVM again if you specify `--dev` @Baccata ? That's the flag to disable the launcher functionality. I bet some logic there is missing an `if (isNativeImage) ...`

> A lot of things are very slow moving so 22.04 is waaay too young to build any tools.
> Plus you barely get any benefits by using it.

I hadn't even considered there was a tradeoff there, just picked latest :)

If any of you want to try your hand at a OR for one of the issues let me know if you need any help. Otherwise I'll get to it soonish

**Comment by Baccata** [comment]
I've managed to run bleep from central, but now it's bloop that's failing to start (and therefore I can't compile stuff) : 

```
📕 command failed [t => 3136 ms]scala.build.blooprifle.FailedToStartServerException: Server didn't start
	at scala.build.blooprifle.internal.Operations$.$anonfun$startServer$8(Operations.scala:240)
	at scala.build.blooprifle.BloopRifleLogger.$anonfun$runnable$1(BloopRifleLogger.scala:13)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I presume it may be a similar issue of incompatible Libc, but not quite sure how to investigate. Regardless, it sounds like fixing the linux version against which bleep is built to ubuntu-20.04 would be a good call.

**Comment by Baccata** [comment]
Let's start with this https://github.com/oyvindberg/bleep/pull/236/files

**Comment by Baccata** [comment]
Alright, making progress. After reading https://github.com/VirtusLab/scala-cli/issues/599, I've bumped the jdk in our CI pipeline to Temurin 17 seems to have done the trick. 

I'm not fully understanding the issue though, I'll have to re-read more closely later.

**Comment by sideeffffect** [comment]
> I've managed to run bleep from central

If you excuse my curiosity, how did you do that?

**Comment by Baccata** [comment]
> > I've managed to run bleep from central
>If you excuse my curiosity, how did you do that?

I used [cs bootstrap](https://get-coursier.io/docs/cli-bootstrap) to download it from maven and bootstrap my own launcher. I could have used `cs launch` too but I'd have to repeat the command, whereas `cs bootstrap`creates a small executable. 

see below for the script : 

``` 
BLEEP_VERSION=$(cat bleep.yaml | grep '$version' | cut -d ":" -f2 |   tr -d ' ')
cs bootstrap build.bleep:bleep-cli_2.13:$BLEEP_VERSION -M bleep.Main -o bleep 
``` 

Other relevant details : 
* I have not set up a JVM within bleep, so it uses my $JAVA_HOME
* I'm running a Java 17 SDK (which seems to be important for the bloop launcher used by bleep)

**Comment by oyvindberg** [comment]
Yeah sorry, should have said that before but am busy. That version of bloop uses named sockets, and only supports JVM 17+

**Comment by Baccata** [comment]
>  Yeah sorry, should have said that before but am busy. That version of bloop uses named sockets, and only supports JVM 17+

No worries whatsoever, I wasn't in a rush

**Comment by oyvindberg** [comment]
to run JVM bleep:
```
cs launch build.bleep::bleep-cli:0.0.1-M22 -M bleep.Main -- --dev
```

I'll add a PR shortly so that `--dev` is not needed

**Comment by oyvindberg** [comment]
version `0.0.1-M23` is out now, built on older ubuntu

**Comment by oyvindberg** [comment]
I think `0.0.1-M23` closed this, reopen if there is still a problem :)
