### ISSUE TITLE
Bleep import fails on Linux

### ISSUE THREAD

**Issue by sbrunk** [oyvindberg/bleep#248]
Tried on an Ubuntu 22.04 machine.

```
❯ bleep import
📗 Will call sbt multiple times to retrieve information about the existing build. Grab some popcorn as it may take a while! [t => 0 ms]
📗 Calling sbt to discover projects... [t => 4 ms]
📙 [subprocess: sbt discover projects]: downloading sbt launcher 1.6.2 [t => 92 ms]
📙 [subprocess: sbt discover projects]: mkdir: cannot create directory '/.cache': Permission denied [t => 93 ms]
📙 [subprocess: sbt discover projects]: mkdir: cannot create directory '/.cache': Permission denied [t => 95 ms]
📙 [subprocess: sbt discover projects]: cat: /.cache/sbt/boot/sbt-launch/1.6.2/sbt-launch-1.6.2.jar.sha1: No such file or directory [t => 96 ms]
📙 [subprocess: sbt discover projects]: shasum: standard input: no properly formatted SHA checksum lines found [t => 109 ms]
📙 [subprocess: sbt discover projects]: failed to download launcher jar: https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.6.2/sbt-launch-1.6.2.jar (shasum mismatch) [t => 109 ms]
📕 Failed external command 'sbt discover projects' with exit code 2. See log file for exact command [t => 110 ms]
```

There seem to be some path issues. It does not recognize the sbt version and makes and absolute path out of the cache dir. I tried with multiple projects with the same result. I also tried to import one of the projects on a Mac machine and the import did work fine here.

**Comment by oyvindberg** [comment]
That's sbt failing when called from bleep. Can you start sbt in that directory?

**Comment by oyvindberg** [comment]
If you add `--debug` to bleep you can see the exact command it tries to run

**Comment by sbrunk** [comment]
> That's sbt failing when called from bleep. Can you start sbt in that directory?

Yes. I actually tried this on my own (currently sbt) project to see how well bleep can work with classifiers for platform dependent native dependencies.

> If you add `--debug` to bleep you can see the exact command it tries to run

Thanks, I'll try that.

**Comment by oyvindberg** [comment]
Interesting, you'll be the first to try :)

One of the integration tests do use them, so there is a chance it'll work. https://github.com/oyvindberg/bleep/blob/e67faf13d3874e241f982fbd7f1e7dcb8f89f969/bleep-site/static/demos/import.yaml#L20

Maybe your SBT launch problem is caused by an old sbt launcher picked up from PATH?

**Comment by sbrunk** [comment]
> Maybe your SBT launch problem is caused by an old sbt launcher picked up from PATH?

There was indeed an sbt 1.6.2 launcher on the path installed as debian package whose sources.list entry got disabled during the latest Ubuntu upgrade. But upgrading it still triggered the same error, just with 1.8.0 now. So I removed that globally installed launcher and now, using the launcher installed via coursier, it's working fine.

It would be interesting to see if someone else can reproduce this with a global sbt installation as debian package. In my case it was installed from the debian repo provided on the sbt website: https://www.scala-sbt.org/download.html

**Comment by oyvindberg** [comment]
Anyway, should probably fix how sbt is run, the code is [here](https://github.com/oyvindberg/bleep/blob/master/bleep-cli/src/scala/bleep/sbtimport/runSbt.scala#L27).

For now it just hands "sbt" to `scala.sys.process.Process`, and that will pick whatever it finds in whatever `$PATH` is active. Maybe `bleep` should just download a new launcher and use that? New launchers should be able to run all older sbt versions afaik

**Comment by sbrunk** [comment]
That would probably more robust yes, always using the launcher that you'd also get via `coursier setup` or `coursier install sbt`. I've just checked and the debian package installs some lengthy shell script as launcher while coursier fetches something that looks like a coursier [bootstrap jar](https://get-coursier.io/docs/cli-bootstrap#bootstraps).
