### ISSUE TITLE
Java properties not set on bleep run

### ISSUE THREAD

**Issue by sbrunk** [oyvindberg/bleep#252]
I keep experimenting with bleep for my project, and running into smaller issues that could be totally my fault using it the wrong way but I think might still make sense to report.

I did an import of my sbt build which sets some java properties when running the main class in a forked JVM, like so:

```scala
    fork    := true,
    javaOptions ++= Seq(
      "-Dfoo=bar",
    ),
```

On import, bleep will generate s.th. like this:

```yaml
    platform:
      jvmOptions: -Dfoo=bar
      name: jvm
```

but the java properties are not set on `bleep run`. So I tried setting `jvmRuntimeOptions: "-Dfoo=bar"` instead without really knowing the difference, but it still does not pick up the properties. Interestingly though, if `jvmRuntimeOptions` are set, and I run `bloop run` manually in`.bleep/builds/normal`, it does pick up the properties.

**Comment by oyvindberg** [comment]
Thanks - by all means report all these small things! :)

**Comment by oyvindberg** [comment]
are you able to figure out with sbt what the semantics are here?
```
runtimeConfig.map(_.options).getOrElse(config.options)
```
or combined them?

**Comment by oyvindberg** [comment]
Yeah, bloop seems to do this:
```
                val javaEnv = project.runtimeJdkConfig.getOrElse(jvm.config)
```
