### ISSUE TITLE
Unable to use run command when running bleep from source

### ISSUE THREAD

**Issue by sbrunk** [oyvindberg/bleep#259]
I'm trying to check if I can set Java properties on my project with your fixes from #253 by running bleep from git, but it seems I'm missing something.

Here's what I did:

```bash
cs install bleep
git clone --recurse-submodules git@github.com:oyvindberg/bleep.git
bleep generate-resources
# edit bleep_git in bleep_dev.sh to repo dir
```

Now in my project I can run a main class without problems:
```bash
bleep run my_project --class Playground # works
```

But using the git version of bleep like so
```bash
/path/to/bleep-repo//bleep_dev.sh run my_project --class Playground
```
fails with the following error:
```
Error: LinkageError occurred while loading main class Playground
        java.lang.ExceptionInInitializerError: null
```

I also tried building a native bleep binary and ran that, but the error is the same. Any idea what I'm missing?

**Comment by sbrunk** [comment]
Ok it looks like this has s.th. to do with #253 because going back to the commit before makes it working again.

It also works correctly if `jvmRuntimeOptions` is set. If it's not, and bleep is using `jvmOpts`, we always get a property `-Duser.dir=${BUILD_DIR}` which I think causes the error. Perhaps `${BUILD_DIR}` needs to be resolved?

**Comment by oyvindberg** [comment]
Thanks for researching it - that seems correct! 

Sorry, I didn't test that fix too carefully, heh.

A possible fix is to pick these values out of `bloopProject` instead, everything is resolved there. The reason I did it this way was it just looked a bit nicer syntactically
