### ISSUE TITLE
arm64 or aarch64 in the channel ? 

### ISSUE THREAD

**Issue by Baccata** [oyvindberg/bleep#267]
On my M1, calling `sys.props("os.arch")` returns `aarch64`

Coursier seems to just pass this information [through]((https://github.com/coursier/coursier/blob/c7f9658419e1fce68e5e0c222523ee8149175bd4/modules/install/src/main/scala/coursier/install/Platform.scala#L10) )  

Bleep however does refer to this architecture as [arm64](https://raw.githubusercontent.com/oyvindberg/bleep/master/coursier-channel.json)

This mistmatches leads coursier to attempt to dynamically rebuild the binary, which fails for an [unrelated reason](https://github.com/coursier/coursier/pull/2649#issuecomment-1370910025). 

I do wonder whether all Apple computers refer to the arch as `aarch64` or whether some of them refer to it as `arm64`. If the former is used, bleep should probably amend the channel, but I'm not 100% certain.

**Comment by oyvindberg** [comment]
Yeah, this was a somewhat tough choice - there is usage of both `arm64` and `aarch64`. For instance coursier JVM downloads uses `arm64`. 

Bleep understands both and produces an ADT in [OsArch](https://github.com/oyvindberg/bleep/blob/master/bleep-model/src/scala/bleep/OsArch.scala#L31-L54). The idea I had is that the ADT does not contain a string version of the arch, but every usage of it should provide the proper arch strings it needs. For instance [FetchJvm](https://github.com/oyvindberg/bleep/blob/master/bleep-model/src/scala/bleep/FetchJvm.scala#L14-L17) and `FetchNode](https://github.com/oyvindberg/bleep/blob/master/bleep-model/src/scala/bleep/FetchNode.scala#L12-L18).

So if something is wrong in the coursier channel we should by all means fix that! :)
It's true that I've had limited/no success in making coursier download arm64 builds, so maybe you're onto something. So far I've attributes the failure to install an arm64 version to my coursier being built for amd64.
