### ISSUE TITLE
Text implicit macro fails when encountering interpolated strings

### ISSUE THREAD

**Issue by Baccata** [oyvindberg/bleep#268]
When implementing a script, this leads to a cryptic compilation error

```scala
val foo = "foo"
started.logger.info(s"$foo")
```

```
📕 BSP: build unclosed string literal [location => file:///private/var/folders/ss/1cdxdk1j36xb7sgmdqsthzy00000gq/T/%3Cconsole%3E:0:9 until 0:9]
```

**Comment by oyvindberg** [comment]
Very strange! I can't really reproduce it with any of 2.12, 2.13 and 3.x.

That said, I'll push a fix to remove some needless complexity in that interface
