### ISSUE TITLE
sourcegen ->  compile -> sourcegen cyclic dependency

### ISSUE THREAD

**Issue by daddykotex** [oyvindberg/bleep#358]
We've hit an issue where `sourcegen` get stuck in a loop.

We have a `protocol` module, with java sources a resources.

The module is laid out like that:
```
> tree protocol/
protocol/
└── src
    ├── main
    │   └── java
    │       └── some
    │           └── package
    │               └── SomeTrait.java
    └── resources
        └── META-INF
            ├── services
            │   └── software.amazon.smithy.model.traits.TraitService
            └── smithy
                ├── manifest
                └── something.smithy
```

I want to generate code from this module using smithy4s. As such, I have a `build` module with a `BleepCodegenScript` class in it. 

```
build
└── src
    └── scala
        └── build
            ├── Smithy4sCodegen.scala // call to smithy4s
            └── Smithy4sSourceGen.scala // BleepCodegenScript 
```

I have a third module, called `core` which has `sourcegen` on it: `sourcegen: build/build.Smithy4sSourceGen`

To invoke the codegen I need to package the `protocol` module as a jar and feed that to the codegen cli. At first it failed because the `jar` did not contain the `classes` for `some.package.SomeTrait`. This happens because Smithy will look at all the jars, load the smithy resources and use java service loader for some things. In this case, my jar contains a service definition under `src/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService` so Smithy tries to load it, but the class is not in the jar.

The fix is to add a `Compile(...).run()` call in the `BleepCodegenScript`. It worked, now the jar contains the classes and the resources. Smithy4s codegen works and write all the files, but when invoked via bleep `sourcegen`,  it gets stuck in a loop.

My understanding is that the `Compile` calls `DoSourceGen`, so we're stuck in a loop.

I'm able to work around the issue by having a custom `Compile` bleep command, like that:

```

// trick to trigger compilation w/o Sourcegen on a specific project
private final case class CustomCompile(
    project: model.CrossProjectName
) extends BleepCommandRemote(watch = false) {

  private val projects = Array(project)

  override def watchableProjects(started: Started): TransitiveProjects =
    TransitiveProjects(started.build, projects)

  override def runWithServer(
      started: Started,
      bloop: BuildServer
  ): Either[BleepException, Unit] = {
    val targets =
      BleepCommandRemote.buildTargets(started.buildPaths, projects)

    val result =
      bloop.buildTargetCompile(new bsp4j.CompileParams(targets)).get()

    result.getStatusCode match {
      case bsp4j.StatusCode.OK =>
        Right(started.logger.info("Compilation succeeded"))
      case other =>
        Left(
          new BspCommandFailed(
            s"compile",
            projects,
            BspCommandFailed.StatusCode(other)
          )
        )
    }
  }
}
```

In this custom command, I rewrote `runWithServer` w/o the `DoSourceGen` bits and it does the trick. Now my `sourcegen` script calls this command instead of compile and it works fine.

Do you think my workaround is sufficient and we should leave the `Compile` implementation as is, or if having a way to avoid `DoSourceGen` when calling `Compile` would make sense?

Thanks again for `bleep`, it's great.

**Comment by oyvindberg** [comment]
Congrats on making it to the most complicated little corner of bleep 🥳

Scanned it on mobile now, so let's see if I got it correctly: 
You can make `build` depend on `protocol`, that means the codegen will be invalidated if anything in protocol changes. And you should have class files and resources from protocol available in a classpath

**Comment by daddykotex** [comment]
I'm sorry for wasting your time. I wrote this long *ss post without going into all the details which left you trying to find a solution for me.

In the end I solved my issue in another way, and I think it is cleaner than the original, I could drop the _custom compile_ command implementation while at it!
