### ISSUE TITLE
incorrect zsh compleation for coursier installations

### ISSUE THREAD

**Issue by ingarabr** [oyvindberg/bleep#375]
Observed on Ubnuntu. 

**Reproduce:**
1. Install bleep using coursier as deceived here: https://bleep.build/docs/installing/
2. Call `bleep install-tab-completions-zsh`
3. Refresh the shell

**Expected:**
auto-completion on the `bleep` command

**Actual:**
auto-completion on the `bleep` does not work. It does however work when using the binary from coursier `.bleep.aux`. 

**Discovery:**
Coursier does wrap the bleep binary (`.bleep.aux`) in a shell script (`bleep`). The command to generate the completion resolves to the binary over the wrapper script. As a temporary workaround I modified the `~/.config/bleep/zsh/_.bleep.aux` script to include the bleep command.

```diff
-#compdef _.bleep.aux .bleep.aux
+#compdef _.bleep.aux .bleep.aux bleep
```

**How to fix it?**
1. Ensure we always add bleep to the compleation as done in the workaround. Can cause issues if we have multiple versions bleep installed and want to keep them separated. 
2. Solve issues with coursier installations: Include some hint about the runtime in [BleepExecutable.scala#L26] . There's already som special handling of java runtime at [BleepExecutable.scala#L74].
3. Generic fix for wrapper scripts: Need more investigation. 

[BleepExecutable.scala#L26]: https://github.com/oyvindberg/bleep/blob/master/bleep-core/src/scala/bleep/BleepExecutable.scala#L26
[BleepExecutable.scala#L74]: https://github.com/oyvindberg/bleep/blob/master/bleep-core/src/scala/bleep/BleepExecutable.scala#L74

**Comment by oyvindberg** [comment]
I think let's just recognize the `.aux` case and add `bleep` as well in that particular case 👍
