### ISSUE TITLE
Documentation for ScalaJS projects

### ISSUE THREAD

**Issue by KaranAhlawat** [oyvindberg/bleep#390]
Is there some documentation in the repo regarding ScalaJS projects? I don't think I missed anything on the https://bleep.build website, and setting up projects for ScalaJS isn't the most straightforward.

For example, what would I need to do to set this `scalaJSUseMainModuleInitializer := true`? And other such stuff.

**Comment by KristianAN** [comment]
hmmm, what does that option do? Bleep supports whatever bloop supports setting through bloop-config.
The state of supported options:

Status:
  - [ ] semantics
  - [X] moduleKind
  - [X ] moduleSplitStyle <- Soon
  - [ ] esFeatures
  - [ ] checkIR
  - [ ] optimizer
  - [ ] jsHeader
  - [ ] parallel
  - [X] sourceMap
  - [ ] relativizeSourceMapBase
  - [ ] outputPatterns
  - [ ] minify
  - [ ] closureCompilerIfAvailable
  - [ ] prettyPrint
  - [ ] batchMode
  - [ ] maxConcurrentWrites
  
 Some of these like closureCompilerIfAvailable and semantics are set by bloop itself.

**Comment by KristianAN** [comment]
looking at the scalajs docs I think scalaJSUseMainModuleInitializer := true is the default behavior, so much so that you can not link unless you explicitly define an object with a main method, which is related to this https://github.com/scalacenter/bloop/issues/1304 I think.

**Comment by oyvindberg** [comment]
@KaranAhlawat The short answer is that support for scala.js in bleep is not finished. it's enough to work on libraries, you can run code, tests and publish. 

What is missing is basically this:
- a `bleep link` command
- the options @KristianAN posted above
- borrow code from relevant sbt plugin(s) to create a nice experience with a bundlers and so on.

Hopefully we'll get there soon

**Comment by KaranAhlawat** [comment]
Can I ask where the `bleep run` commands puts the linked files? I think from the conversation so far the support should be enough for my usecase. *Hopefully :D*

**Comment by KristianAN** [comment]
the linked files end up in .bleep/builds/normal/.bloop/<project>/<project>-js

**Comment by KaranAhlawat** [comment]
Alright, then I suppose we can close this issue.
