### ISSUE TITLE
[BUG] --strict does not work on Scala 3.5.0 -Ykind-projector is deprecated

### ISSUE THREAD

**Issue by KristianAN** [oyvindberg/bleep#401]
this is fixed here: https://github.com/typelevel/scalac-options/pull/131

I am not entirely sure how the bleep sbt-tpolecat (or rather liberated plugins) interaction works. In any case the strict flag is blocked on 3.5.0 by this.

**Comment by oyvindberg** [comment]
It's easy once you understand it, heh.

The liberated modules are all git submodules. You cd into the corresponding folder, add a git remote which corresponds to upstream, rebase on top, push changes and commit the changed commit reference in a bleep branch.

Note that it's all currently set up to rebase, which is a terrible decision. We should use merges so we don't lose old SHAs for consistent builds

**Comment by oyvindberg** [comment]
Fixed in #421
