### ISSUE TITLE
poor error reporting through cli 

### ISSUE THREAD

**Issue by KristianAN** [oyvindberg/bleep#405]
Introducing an error in my project and compiling with bleep compile project

the output looks like this
📕 BSP: server Not found: type IO [value => 6]
📕 BSP: server Not found: type IO [value => 6]
📕 BSP: server Not found: Resource [value => 6]
📕 BSP: server Not found: type IO [value => 6]
📕 BSP: server Not found: type IO [value => 6]
📕 BSP: server Not found: type ExitCode [value => 6]
📕 BSP: server Not found: type IO [value => 6]
📕 BSP: server Not found: type IO [value => 6]
📕 BSP: server Not found: type IO [value => 6]
📕 BSP: server Not found: type IO [value => 6]
📕 BSP: server Not found: type IO [value => 6]
📕 command failed: compile server failed status code ERROR

The error is clear, but the origin is completely lost.

Looking at the errors reported by metals in neovim we can see that it reports them as such
    ~/src/roskva/server/src/scala/no/hnikt/etl/server/  11 
   └╴  Server.scala  11 
     ├╴E Not found: type IO bloop (6) [36, 33]
     ├╴E Not found: type IO bloop (6) [37, 37]
     ├╴E Not found: Resource bloop (6) [40, 21]
     ├╴E Not found: type IO bloop (6) [46, 33]
     ├╴E Not found: type IO bloop (6) [46, 39]
     ├╴E Not found: type ExitCode bloop (6) [46, 42]
     ├╴E Not found: type IO bloop (6) [47, 27]
     ├╴E Not found: type IO bloop (6) [58, 6]
     ├╴E Not found: type IO bloop (6) [59, 27]
     ├╴E Not found: type IO bloop (6) [59, 55]
     └╴E Not found: type IO bloop (6) [64, 46]
Here the file and line origin is preserved. 

the  expected outcome here is that compiling through the cli should show the same errors as metals. 

Note that this is not always the case, sometimes bleep does show the origin of the error. I am not sure what causes it not to.

**Comment by oyvindberg** [comment]
seems to finally be fixed now with bleep 0.0.6 and scala 3.4.2 . can you check?

**Comment by KristianAN** [comment]
> seems to finally be fixed now with bleep 0.0.6 and scala 3.4.2 . can you check?

I tried with 0.0.6 and Scala 3.4.2
> 📕 BSP: server-integration-tests-test Not found: type IO [value => 6]
  📕 BSP: server-integration-tests-test Not found: type IO [value => 6]
  
So it does not seem like it's fixed yet.

**Comment by KristianAN** [comment]
if you comment out this line
https://github.com/oyvindberg/bleep/blob/63cca631fad7547aec6c7e6500ccf1db9764db9d/bleep-core/src/scala/bleep/internal/BspClientDisplayProgress.scala#L131
the location of the error appears in the build output again.

**Comment by oyvindberg** [comment]
Really?! Interesting!

**Comment by oyvindberg** [comment]
thanks for the hint @KristianAN - that was actually it! I removed some "convenience" macros now :)

**Comment by oyvindberg** [comment]
fixed in #422
