### ISSUE TITLE
[BUG] Spam to .bleep/builds/bsp/last.log causing high cpu usage and massive filesize

### ISSUE THREAD

**Issue by KristianAN** [oyvindberg/bleep#409]
When running with metals the last.log file is filled with
[debug] 2024-08-08T19:20:29.066709Z FileWatching.scala:42 Event(/home/kristian/src/roskva/.bleep/builds/bsp/last.log, Modify)

The file quickly grows into the GiBs.

**Comment by KristianAN** [comment]
Killing the metals process stops the spam

**Comment by oyvindberg** [comment]
oh you filed it here - great! hopefully fixed by #410

**Comment by oyvindberg** [comment]
this is fixed now right @KristianAN ?

**Comment by KristianAN** [comment]
> this is fixed now right @KristianAN ?

Yes, this seems to be fixed.
